[package]
name = "kate-ptau-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-std = { version = "0.3", features = ["parallel"]}
ark-ff = { version = "0.3" }
ark-ec = { version = "0.3" }
ark-serialize = { version = "0.3" }
ark-bls12-381 = { version = "0.3", features = ["curve"] }
rand = "0.8.4"
eyre = "0.6.8"
kzg-ceremony-coordinator = { git = "https://github.com/recmo/kzg-ceremony-coordinator" }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
axum = "0.5.15"
ruint = { version = "1.3.0", features = ["serde", "ark-ff"] }
valico = "3.6.1"
tracing = "0.1"
hex = "0.4.3"
rayon = "1.5.3"